<a href="https://colab.research.google.com/github/volodymyr-holovan/DTA2026/blob/main/project_store_sales_analysis/store_sales_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Запусти цей блок, щоб отримати датасет
import pandas as pd
import numpy as np

np.random.seed(42)
n = 300

categories = ['Молочне', 'Хліб та випічка', 'М\'ясо та риба', 'Овочі та фрукти', 'Напої']
products = {
    'Молочне':          ['Молоко 1л', 'Кефір 0.5л', 'Сир кисломолочний', 'Масло вершкове', 'Йогурт'],
    'Хліб та випічка':  ['Хліб білий', 'Батон', 'Булочка', 'Хліб житній', 'Круасан'],
    'М\'ясо та риба':   ['Куряче філе', 'Свинина', 'Ковбаса', 'Риба хек', 'Сосиски'],
    'Овочі та фрукти':  ['Картопля', 'Морква', 'Яблука', 'Банани', 'Помідори'],
    'Напої':            ['Вода 1.5л', 'Сік апельсиновий', 'Чай', 'Кава мелена', 'Лимонад'],
}
prices = {
    'Молоко 1л': 38, 'Кефір 0.5л': 22, 'Сир кисломолочний': 55, 'Масло вершкове': 95, 'Йогурт': 30,
    'Хліб білий': 28, 'Батон': 25, 'Булочка': 12, 'Хліб житній': 32, 'Круасан': 18,
    'Куряче філе': 165, 'Свинина': 210, 'Ковбаса': 145, 'Риба хек': 120, 'Сосиски': 98,
    'Картопля': 20, 'Морква': 15, 'Яблука': 45, 'Банани': 52, 'Помідори': 60,
    'Вода 1.5л': 18, 'Сік апельсиновий': 68, 'Чай': 85, 'Кава мелена': 155, 'Лимонад': 35,
}

chosen_cats = np.random.choice(categories, n, p=[0.25, 0.20, 0.20, 0.20, 0.15])
chosen_products = [np.random.choice(products[c]) for c in chosen_cats]

df_origin = pd.DataFrame({
    'transaction_id': range(1001, 1001 + n),
    'date':           pd.to_datetime(
                          np.random.choice(pd.date_range('2024-03-01', '2024-03-31'), n)
                      ),
    'hour':           np.random.choice(range(8, 21), n, p=[0.04,0.06,0.08,0.10,0.12,0.12,0.11,0.10,0.09,0.08,0.06,0.04,0.00]),
    'category':       chosen_cats,
    'product':        chosen_products,
    'quantity':       np.random.randint(1, 6, n),
    'price_uah':      [prices[p] for p in chosen_products],
    'customer_age':   np.random.randint(18, 70, n),
    'payment':        np.random.choice(['Готівка', 'Картка', 'Телефон'], n, p=[0.35, 0.50, 0.15]),
})

In [ ]:
df = df_origin.copy()

#Блок 1 - Перше знайомство з даними
- Виведи перші 7 рядків датафрейму.
- Дізнайся розмір таблиці (рядки × стовпці).
- Виведи типи даних кожного стовпця.
- Перевір, чи є пропущені значення.
- Виведи основну статистику (describe) для числових стовпців.
> **Питання:** Яка середня сума однієї покупки? Чи є підозрілі мінімуми/максимуми?

1. Виведи перші 7 рядків датафрейму.

In [ ]:
df.head(7)

,transaction_id,date,hour,category,product,quantity,price_uah,customer_age,payment
0,1001,2024-03-17,17,Хліб та випічка,Круасан,4,18,28,Готівка
1,1002,2024-03-13,14,Напої,Кава мелена,3,155,40,Картка
2,1003,2024-03-01,18,Овочі та фрукти,Яблука,1,45,43,Картка
3,1004,2024-03-02,8,М'ясо та риба,Риба хек,3,120,51,Готівка
4,1005,2024-03-09,19,Молочне,Йогурт,5,30,63,Картка
5,1006,2024-03-03,13,Молочне,Кефір 0.5л,3,22,51,Картка
6,1007,2024-03-31,15,Молочне,Масло вершкове,2,95,46,Телефон

2. Дізнайся розмір таблиці (рядки × стовпці).

In [ ]:
print(f"Розмір: {df.shape[0]} рядків х {df.shape[1]} стовпців")

Розмір: 300 рядків х 9 стовпців

3. Виведи типи даних кожного стовпця.

In [ ]:
df.dtypes

transaction_id             int64
date              datetime64[ns]
hour                       int64
category                  object
product                   object
quantity                   int64
price_uah                  int64
customer_age               int64
payment                   object
dtype: object

4. Перевір, чи є пропущені значення.

In [ ]:
df.isnull().sum()

transaction_id    0
date              0
hour              0
category          0
product           0
quantity          0
price_uah         0
customer_age      0
payment           0
dtype: int64

5. Виведи основну статистику (`describe`) для числових стовпців.

In [ ]:
print("Статистика:")
df.describe().round(2)

Статистика:

,transaction_id,date,hour,quantity,price_uah,customer_age
count,300.00,300,300.00,300.00,300.00,300.0
mean,1150.50,2024-03-16 02:14:24,13.72,2.97,63.45,43.0
min,1001.00,2024-03-01 00:00:00,8.00,1.00,12.00,18.0
25%,1075.75,2024-03-08 00:00:00,12.00,2.00,22.00,31.0
50%,1150.50,2024-03-16 12:00:00,14.00,3.00,38.00,42.5
75%,1225.25,2024-03-24 00:00:00,16.00,4.00,95.75,55.0
max,1300.00,2024-03-31 00:00:00,19.00,5.00,210.00,69.0
std,86.75,NaN,2.74,1.44,51.68,14.6

Висновок:Датасет містить **300 транзакцій** без пропущених значень. Середня сума однієї покупки — **~187 грн**. Мінімум (12 грн) відповідає 1 булочці, максимум (840 грн) — 5 кг свинини. Підозрілих аномалій немає.

### Блок 2 - Фільтрація та відбір

1. Відбери всі покупки категорії **«М'ясо та риба»**.
2. Знайди транзакції, де сума (`total_uah`) перевищує **500 грн**.
3. Відбери покупки, зроблені **карткою** (`payment == 'Картка'`), кількістю **більше 2 одиниць**.
4. Знайди всі покупки покупців **молодше 25 років**.
5. Скільки унікальних товарів є в датасеті?
> **Питання:** Який відсоток транзакцій перевищує 500 грн?

1. Відбери всі покупки категорії **«М'ясо та риба»**.

In [17]:
meat = df[df['category'] == "М'ясо та риба"]
print(f"1. Покупки 'М'ясо та риба': {len(meat)} транзакцій")
meat.head(3)

1. Покупки 'М'ясо та риба': 61 транзакцій

,transaction_id,date,hour,category,product,quantity,price_uah,customer_age,payment
3,1004,2024-03-02,8,М'ясо та риба,Риба хек,3,120,51,Готівка
8,1009,2024-03-21,15,М'ясо та риба,Ковбаса,2,145,34,Картка
17,1018,2024-03-06,14,М'ясо та риба,Куряче філе,3,165,69,Картка

2. Знайди транзакції, де сума (`total_uah`) перевищує **500 грн**.

In [30]:
df[df['price_uah'] * df['quantity']> 500]

,transaction_id,date,hour,category,product,quantity,price_uah,customer_age,payment
24,1025,2024-03-10,14,М'ясо та риба,Свинина,4,210,28,Картка
28,1029,2024-03-21,14,М'ясо та риба,Куряче філе,4,165,61,Готівка
81,1082,2024-03-02,16,М'ясо та риба,Ковбаса,4,145,53,Картка
89,1090,2024-03-20,15,М'ясо та риба,Риба хек,5,120,28,Готівка
93,1094,2024-03-24,14,М'ясо та риба,Свинина,3,210,38,Картка
96,1097,2024-03-30,14,М'ясо та риба,Свинина,3,210,35,Картка
101,1102,2024-03-05,16,М'ясо та риба,Свинина,3,210,49,Картка
103,1104,2024-03-04,14,М'ясо та риба,Куряче філе,5,165,62,Картка
146,1147,2024-03-19,10,М'ясо та риба,Риба хек,5,120,67,Картка
147,1148,2024-03-19,13,М'ясо та риба,Куряче філе,5,165,32,Готівка
187,1188,2024-03-17,13,М'ясо та риба,Свинина,4,210,29,Картка
193,1194,2024-03-31,16,М'ясо та риба,Куряче філе,4,165,63,Картка
203,1204,2024-03-13,11,Напої,Кава мелена,5,155,35,Телефон
221,1222,2024-03-03,9,М'ясо та риба,Риба хек,5,120,38,Картка
241,1242,2024-03-25,19,Напої,Кава мелена,5,155,51,Картка
263,1264,2024-03-20,13,М'ясо та риба,Риба хек,5,120,59,Готівка
273,1274,2024-03-01,11,Напої,Кава мелена,4,155,64,Картка

3. Відбери покупки, зроблені **карткою** (`payment == 'Картка'`), кількістю **більше 2 одиниць**.

In [26]:
df[(df['payment'] == 'Картка') & (df['quantity'] > 2)]

,transaction_id,date,hour,category,product,quantity,price_uah,customer_age,payment
1,1002,2024-03-13,14,Напої,Кава мелена,3,155,40,Картка
4,1005,2024-03-09,19,Молочне,Йогурт,5,30,63,Картка
5,1006,2024-03-03,13,Молочне,Кефір 0.5л,3,22,51,Картка
10,1011,2024-03-23,13,Молочне,Сир кисломолочний,5,55,30,Картка
17,1018,2024-03-06,14,М'ясо та риба,Куряче філе,3,165,69,Картка
...,...,...,...,...,...,...,...,...,...
289,1290,2024-03-23,18,М'ясо та риба,Сосиски,4,98,57,Картка
291,1292,2024-03-23,14,Молочне,Молоко 1л,3,38,53,Картка
292,1293,2024-03-03,18,Овочі та фрукти,Морква,3,15,62,Картка
294,1295,2024-03-31,18,Молочне,Сир кисломолочний,5,55,64,Картка
297,1298,2024-03-04,11,Молочне,Молоко 1л,3,38,27,Картка

4. Знайди всі покупки покупців **молодше 25 років**.

In [27]:
df[df['customer_age'] < 25]

,transaction_id,date,hour,category,product,quantity,price_uah,customer_age,payment
7,1008,2024-03-01,17,Напої,Сік апельсиновий,1,68,21,Готівка
19,1020,2024-03-21,16,Хліб та випічка,Круасан,1,18,19,Готівка
26,1027,2024-03-19,13,Молочне,Йогурт,3,30,20,Готівка
36,1037,2024-03-04,14,Хліб та випічка,Круасан,1,18,23,Телефон
38,1039,2024-03-01,10,Овочі та фрукти,Помідори,1,60,22,Готівка
39,1040,2024-03-17,17,Хліб та випічка,Хліб житній,1,32,20,Картка
40,1041,2024-03-08,16,Молочне,Йогурт,4,30,18,Готівка
65,1066,2024-03-31,14,М'ясо та риба,Свинина,2,210,24,Картка
66,1067,2024-03-15,13,Молочне,Молоко 1л,4,38,20,Телефон
70,1071,2024-03-21,14,Овочі та фрукти,Банани,2,52,20,Готівка
77,1078,2024-03-28,15,Молочне,Сир кисломолочний,3,55,24,Готівка
86,1087,2024-03-19,16,Овочі та фрукти,Банани,5,52,19,Готівка
129,1130,2024-03-31,10,М'ясо та риба,Сосиски,4,98,19,Картка
141,1142,2024-03-27,12,Хліб та випічка,Хліб житній,1,32,19,Телефон
154,1155,2024-03-22,8,Напої,Чай,2,85,20,Картка
155,1156,2024-03-21,18,Молочне,Масло вершкове,1,95,23,Картка
157,1158,2024-03-01,14,Овочі та фрукти,Банани,2,52,23,Готівка
171,1172,2024-03-25,11,Молочне,Сир кисломолочний,2,55,24,Картка
175,1176,2024-03-15,13,Молочне,Молоко 1л,3,38,21,Картка
176,1177,2024-03-24,16,Овочі та фрукти,Морква,5,15,23,Готівка
179,1180,2024-03-31,14,Молочне,Молоко 1л,1,38,20,Готівка
202,1203,2024-03-02,14,Молочне,Йогурт,3,30,23,Готівка
209,1210,2024-03-07,17,Молочне,Йогурт,4,30,20,Картка
217,1218,2024-03-13,18,Овочі та фрукти,Картопля,2,20,24,Готівка
226,1227,2024-03-05,17,Напої,Вода 1.5л,1,18,21,Телефон
239,1240,2024-03-13,17,Молочне,Сир кисломолочний,5,55,19,Готівка
243,1244,2024-03-10,10,Хліб та випічка,Батон,1,25,23,Готівка
249,1250,2024-03-04,13,Напої,Вода 1.5л,2,18,20,Картка
267,1268,2024-03-24,15,Овочі та фрукти,Банани,1,52,19,Телефон
269,1270,2024-03-13,10,Хліб та випічка,Хліб білий,4,28,22,Готівка
278,1279,2024-03-06,13,Овочі та фрукти,Яблука,3,45,19,Картка
280,1281,2024-03-16,13,Напої,Сік апельсиновий,4,68,23,Картка
284,1285,2024-03-30,9,М'ясо та риба,Свинина,2,210,19,Готівка
287,1288,2024-03-31,17,М'ясо та риба,Ковбаса,2,145,22,Готівка
288,1289,2024-03-24,13,Хліб та випічка,Круасан,5,18,18,Телефон
298,1299,2024-03-24,14,М'ясо та риба,Ковбаса,1,145,20,Готівка

5. Скільки унікальних товарів є в датасеті?

In [28]:
df['product'].nunique()

25

Висновок:Лише 17 транзакцій перевищують 500 грн — це переважно купівля м'яса/риби у великій кількості. Більшість покупок — побутові, до 300 грн.